package com.minhcraft.beyondbetatweaks.mixin.feature.bedrock_egg;

import com.minhcraft.beyondbetatweaks.BeyondBetaTweaks;
import com.minhcraft.beyondbetatweaks.world.bedrock_egg.BedrockEggBuilder;
import com.minhcraft.beyondbetatweaks.world.bedrock_egg.BedrockEggState;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.chunk.ChunkStatus;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(ServerLevel.class)
public abstract class ServerLevelMixin {

    @Inject(method = "tick", at = @At("HEAD"))
    private void beyond_beta_tweaks$generateBedrockEgg(java.util.function.BooleanSupplier hasTimeLeft, CallbackInfo ci) {
        ServerLevel self = (ServerLevel) (Object) this;

        // Only in the overworld
        if (self.dimension() != Level.OVERWORLD) return;

        BedrockEggState state = BedrockEggState.get(self);
        if (state.isEggPlaced()) return;

        // Check 4 chunks: (-1,-1), (-1,0), (0,-1), (0,0).
        // All must be fully generated before we can place the egg.
        for (int cx = -1; cx <= 0; cx++) {
            for (int cz = -1; cz <= 0; cz++) {
                var chunk = self.getChunkSource().getChunkNow(cx, cz);
                if (chunk == null) return;
                if (!chunk.getStatus().isOrAfter(ChunkStatus.FULL)) return;
            }
        }

        // Ensure the area is generated by force-loading the chunks temporarily
        // The 5x5 structure centered at 0,0 fits in a single chunk (or at most 4)
        for (int cx = -1; cx <= 0; cx++) {
            for (int cz = -1; cz <= 0; cz++) {
                if (self.getChunk(cx, cz) == null) return;
            }
        }

        int eggY = BedrockEggBuilder.calculateEggY(self);
        BedrockEggBuilder.clearVegetation(self, eggY);
        BedrockEggBuilder.buildSealedEgg(self, eggY);

        state.setEggY(eggY);
        state.setEggPlaced(true);

        BeyondBetaTweaks.LOGGER.debug("Bedrock egg placed at y={}", eggY);

        // Force re-sync the 4 affected chunks to all connected players
        // to prevent client-server desync where the client has stale terrain data
        for (int cx = -1; cx <= 0; cx++) {
            for (int cz = -1; cz <= 0; cz++) {
                var chunk = self.getChunkSource().getChunkNow(cx, cz);
                if (chunk != null) {
                    for (ServerPlayer player : self.players()) {
                        player.connection.send(
                                new net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket(
                                        chunk, self.getLightEngine(), null, null
                                )
                        );
                    }
                }
            }
        }
    }
}
