package com.minhcraft.beyondbetatweaks.mixin.feature.bedrock_egg;

import com.minhcraft.beyondbetatweaks.BeyondBetaTweaks;
import com.minhcraft.beyondbetatweaks.world.BedrockEggBuilder;
import com.minhcraft.beyondbetatweaks.world.BedrockEggState;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.Level;
import org.spongepowered.asm.mixin.Mixin;
import org.spongepowered.asm.mixin.injection.At;
import org.spongepowered.asm.mixin.injection.Inject;
import org.spongepowered.asm.mixin.injection.callback.CallbackInfo;

@Mixin(ServerLevel.class)
public abstract class ServerLevelMixin {

    @Inject(method = "tick", at = @At("HEAD"))
    private void beyond_beta_tweaks$generateBedrockEgg(java.util.function.BooleanSupplier hasTimeLeft, CallbackInfo ci) {
        ServerLevel self = (ServerLevel) (Object) this;

        // Only in the overworld
        if (self.dimension() != Level.OVERWORLD) return;

        BedrockEggState state = BedrockEggState.get(self);
        if (state.isEggPlaced()) return;

        // Check if the chunk at 0,0 is loaded (it should be soon after world gen)
        if (!self.isLoaded(new net.minecraft.core.BlockPos(0, 0, 0))) return;

        // Ensure the area is generated by force-loading the chunks temporarily
        // The 5x5 structure centered at 0,0 fits in a single chunk (or at most 4)
        for (int cx = -1; cx <= 0; cx++) {
            for (int cz = -1; cz <= 0; cz++) {
                if (self.getChunk(cx, cz) == null) return;
            }
        }

        int eggY = BedrockEggBuilder.calculateEggY(self);
        BedrockEggBuilder.clearVegetation(self, eggY);
        BedrockEggBuilder.buildSealedEgg(self, eggY);

        state.setEggY(eggY);
        state.setEggPlaced(true);

        BeyondBetaTweaks.LOGGER.debug("Bedrock egg placed at y={}", eggY);
    }
}
